### ISSUE TITLE
dec64_sin() might never return, and now accurately can one reduce radians?

### ISSUE THREAD

**Issue by jejones3141** [douglascrockford/DEC64#11]
dec64_sin() doesn't check for radians values of magnitude large enough that subtracting or adding 2*pi doesn't change it; for such values dec64_sin() will never return.

Simple methods of reducing radians may be so inaccurate as to give a meaningless result for large magnitudes. Looks like there is a way around that (http://www.csee.umbc.edu/~phatak/645/supl/Ng-ArgReduction.pdf), though ultimately radians may be the result of a calculation which itself is subject to error and has a result where the next larger and next smaller DEC64 number are a significant fraction of 2*pi or even vastly more than 2*pi apart--in that case can one really claim to be able to calculate the sine accurately?

(Speaking of argument reduction--you can reduce it to between -pi/2 and pi/2; that should give a more accurate result with the Taylor series.)

**Comment by douglascrockford** [comment]
This file is a placeholder. It should be replaced with functions that are
faster and more accurate.
