### ISSUE TITLE
Could you please include a simple javascript version :)

### ISSUE THREAD

**Issue by kristianmandrup** [douglascrockford/DEC64#12]
Something like this (perhaps with optional `new`)

```
x = new Dec64(0.1)
y = new Dec64(0.2)
z = x + y
console.log(z) // 0.3
```

Could be useful for the brave including those of us who experiment with creating new languages that compile to JavaScript. I see Rust has adopted dec64 already.
Cheers!

**Comment by douglascrockford** [comment]
Things like

    z = x + y;

Require a change to the standard. 

Don't forget your semicolons.

**Comment by mvasilkov** [comment]
Semicolons aren't required by the standard though. Thankfully, we have ASI
for those.

**Comment by kristianmandrup** [comment]
I spent all morning trying to find a way to port this lib for use in Javascript or Node.js

I tried a few disassemblers, such as [onlinedisassembler](https://www.onlinedisassembler.com) but been a Looong time since I played with asm code at uni and not sure how to configure the disassembler to read/parse the code correctly. 

Also tried Hopper, but only produces pseudo-code. All I need is to convert the `dec64.asm` to C code, then use `emscripten` via [require-emscripten](https://www.npmjs.com/package/require-emscripten) to use it from Node.js I think.

Please advice. Thanks!

**Comment by kristianmandrup** [comment]
Looks like the best (easiest?) option is to convert it to [asm.js](http://asmjs.org/spec/latest/) or [SIMD](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SIMD) "browser compatible" assembly.

**Comment by kristianmandrup** [comment]
So far I found this nice [recipe](http://reverseengineering.stackexchange.com/questions/10924/translate-assembly-to-c) :)

**Comment by lpsantil** [comment]
If DEC64 were to be picked up by TC-39, (ideally) it might not need a new Object type and semantics added to the language.

A better example could be
```
// using # or @ symbol to update the semantics, pi * r^2 is not representable at this
// precision with JS currently, say for the area covered by the Milky Way -
// https://imagine.gsfc.nasa.gov/features/cosmic/milkyway_info.html
var mwArea_km = pi64 * #500000000000000000 * #500000000000000000;
```

Even better would be a way to not introduce additional character spew (aka unnatural notation).

**Comment by douglascrockford** [comment]
TC39 won't do it. Think about putting it into a new, better language.
