### ISSUE TITLE
test_new and testing exact matches.

### ISSUE THREAD

**Issue by graffic** [douglascrockford/DEC64#13]
From all the tests in `test_all_new` function from `dec64_test.c` Only one is not an exact match of the expected dec64 number. (line 1123).

`test_new(-368934881474191049, 0, (-368934881474191 << 8) + 3, "-368934881474191049");`

I'd like to suggest to change the expected number to the exact match and remove the compare-with-normalise step in `judge_not`.

I believe it will help readers to understand how the `dec64_new` function works. In my personal case it took me some time to realise that the normalisation step was there, just for one case. But perhaps I'm missing something.

**Comment by douglascrockford** [comment]
That one case is an important one.

**Comment by graffic** [comment]
Why is that one case important?

I'm missing something. Could you help me to find that something out? Let me share with you what I understand about that test case so you can point out what is missing or what I'm not considering important.

My understanding of that specific case is that the expected number is given to the `normal` test function, its exponent is reduced by one (and the coefficient multiplied by 10), and the result becomes the new expected. This is the only case where the `normal` function changes the any of the numbers (expected or actual), and it only changes the expected number.
