### ISSUE TITLE
What about saturation arithmetic?

### ISSUE THREAD

**Issue by leo-yuriev** [douglascrockford/DEC64#14]
https://en.wikipedia.org/wiki/Saturation_arithmetic

**Comment by douglascrockford** [comment]
That is usually an int thing. DEC64 is a floating point thing.

**Comment by Amaroq-Clearwater** [comment]
Yes, but this is still a valid thing to consider addressing in the Readme.

**Comment by douglascrockford** [comment]
No it isn't.

**Comment by erthink** [comment]
For clarification, "saturation" for float point is a `DBL_MAX + DBL_MAX` => `INFINITY`, etc.

**Comment by douglascrockford** [comment]
DEC64 produces null in that case.

**Comment by erthink** [comment]
> DEC64 produces null in that case.

imho this should be noted, but I would prefer saturation for this case and the `NaN` (i.e `null`) for others.
Nonetheless, thank you for DEC64!

**Comment by douglascrockford** [comment]
DEC64 finds the closest representation. If no representation is possible, it gives null. Infinity is as far away from a correct answer that can be imagined.
