### ISSUE TITLE
C implementation? 

### ISSUE THREAD

**Issue by exebook** [douglascrockford/DEC64#18]
Hi, I am implementing my own programing language, I am at that point where I can choose the number representation. Right now I have tested fixed point numbers and was surprised how fast they are, basically no benchmark shown any difference from plain ints. That's with gcc -O3 or clang -O2. Without the optimisation switch, speed is 5-100 worse depending on the compiler / optimisation (TinyC is very slow on this).

Now I want to try DEC64, but I do not want to use assembly at the moment. Do you happen by any chance to have a plain C implementation at least for basics (i. e. convert to/from int/double, add/multiply)? Or was your first prototype built in asm from the very beginning? 

Other question is about 64 bits, I can only use 63 bits, because I need one bit for pointer tagging for the VM. What would be a solution here (for DEC63), reduce the magnitude bits?

Also I use this chance to thank you for the example TDOP compiler you have here, reading it's code and related text inspired me very much!

**Comment by douglascrockford** [comment]
Currently the only implementation is x64 assembly language. But the obj it produces can be linked with C.

DEC64 does tagging differently. If the exponent is not 0x80, then all 64 bits are number. If the exponent is 0x80, then the remaining 56 bits are yours. That is plenty for tagged object pointers or anything else you might want.
