### ISSUE TITLE
Decimals are not always exact.

### ISSUE THREAD

**Issue by bab9e9** [douglascrockford/DEC64#25]
Sure, if you consider only decimal input strings it is, trivally, exact. But numbers also come from calculations and division is not always exact.
For example add this to tests.

    // Using decimal doesn't solve every representation problem.
    // Namely 1/3 is not exactly representable in dec64.
    // So, for example, a three-way stock split isn't exact. 
    test_add(dec64_divide(one, three), dec64_divide(one, three), dec64_divide(two, three), , "1/3 + 1/3 =? 2/3");  // fails!, I expect

**Comment by douglascrockford** [comment]
Neither are the real numbers.

**Comment by jglathe** [comment]
A pass would raise anneyebrow, though.
