### ISSUE TITLE
DEC64 counterpart: DEC64unbiased

### ISSUE THREAD

**Issue by dumblob** [douglascrockford/DEC64#28]
### Motivation

Statistical computations, financial computations, simulations, statistical proving systems (e.g. diehard, [dieharder](https://github.com/betrusted-io/betrusted-soc/issues/13#issuecomment-777238911 ), STS, ...), etc. need provably unbiased rounding. Unfortunately DEC64 uses e.g. biased rounding and thus is not suitable for these domains which seems to non-negligibly limit its use.

### Proposal

Create a separate DEC64-based standard `DEC64unbiased`, which will provide all functionality as DEC64, but will also **guarantee** unbiased computation (especially rounding) by employing the [Alternating tie-breaking technique](https://en.wikipedia.org/wiki/Rounding#Alternating_tie-breaking ) or alike (though I don't know of any other providing this **guarantee** - all others are just converging to the optimum, but they do not **guarantee** anything).

### Alternatives considered

1. Changing DEC64 by providing such **guarantee**. Not viable because it's expected that **guaranteeing** unbiased computation will have negative impact on performance.

2. Changing DEC64 so that it provides "rounding modes". Not viable as any modality (modes, options, ...) proved problematic - at least with IEEE 754 etc. The goal is to have something fixed without any way to "get astray".

**Comment by douglascrockford** [comment]
It is needed because of the inability to accurately represent the decimal fractions. Nearly every number containing a decimal point contains a small amount of error. Over the course of a computation, that error can become significant. Alternate tie breaking can disguise that situation in some cases, but can exasperate it in others.

You are free to implement an unbiased, but I think it is unnecessary.

**Comment by dumblob** [comment]
>It is needed because of the inability to accurately represent the decimal fractions. Nearly every number containing a decimal point contains a small amount of error. Over the course of a computation, that error can become significant. Alternate tie breaking can disguise that situation in some cases, but can exasperate it in others.

Just to clarify, I meant strictly bias, not error. In other words, I'm fine if I'm 50% off from the correct result if and only if any subsequent result will be also 50% off (i.e. any short sequence of results - ideally any 2 consecutive results - has to show no bias despite the error is huge).

>You are free to implement an unbiased, but I think it is unnecessary.

Do you mean you'll not claim any DEC64 brand, copyright, whatsoever if anyone does that (even if e.g. DEC64unbiased implementation was wrong or against the goals of DEC64 and thus shedded a really bad light on DEC64 itself)?

Or do you mean "if you want to implement it, do it in any way you like and I hereby promise to merge such a pull request"?

**Comment by douglascrockford** [comment]
It is Public Domain.

I will merge only if I am convinced it is necessary and beneficial.

**Comment by dumblob** [comment]
Ok, good, thanks. I just wanted to be sure (as anything floating point related is a high-stake game).

**Comment by Amaroq-Clearwater** [comment]
For context, could you provide a summarized or simplified explanation of Bias?

**Comment by douglascrockford** [comment]
See the IEEE 754 Standard.
