### ISSUE TITLE
How does DEC64 relate to the IEEE "decimal64" format?

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [douglascrockford/DEC64#29]
I was having a conversation with a friend about DEC64, and he brought up the "decimal64" IEEE format, and now I feel the need to ask...
https://en.wikipedia.org/wiki/Decimal64_floating-point_format

How are these two formats (DEC64 versus decimal64) related, and how would I go about convincing somebody that one is better than the other?

(On record, IBM had started implementing decimal64 directly into their hardware not long after the format was formally specified.)

**Comment by douglascrockford** [comment]
IBM's format puts three digits in a 10 bit field. Implementation is very complex. IBM was unable to convince Intel or ARM to implement it. DEC64 is much simpler.

**Comment by JensGrabner** [comment]
Here you found Information about the .. "IEEE754-2008 (DPD & BID Encodings)"
https://github.com/libdfp/libdfp
