### ISSUE TITLE
sqrt hangs on some inputs

### ISSUE THREAD

**Issue by devast8a** [douglascrockford/DEC64#32]
For some inputs `dec64_sqrt` can enter an infinite loop where it will not converge on a result and will instead oscillate between two values forever. It seems to be related to rounding behavior within `dec64_divide`. Printing both the coefficient and the exponent of `progress`, we get the following log from `dec64_sqrt(dec64_make(36040, 0))`

```
9011000000000000 -12
4507499778049051 -12
22577476706966965 -13
11368552409916279 -13
5842783632731283 -13
3229806454536597 -13
2172831395833602 -13
19157483389377885 -14
18984987616317365 -14
1898420397630861 -13
18984203960134855 -14
1898420396013486 -13
18984203960134855 -14
1898420396013486 -13
18984203960134855 -14
1898420396013486 -13
18984203960134855 -14
1898420396013486 -13
18984203960134855 -14
1898420396013486 -13
...
```

**Comment by douglascrockford** [comment]
So what is your fix?

**Comment by devast8a** [comment]
Not sure, bounding the loop might be acceptable in the short term. In the long term, probably adopting another algorithm.

**Comment by douglascrockford** [comment]
Please submit a fix.
