### ISSUE TITLE
divide produces different results for different representations of the same inputs

### ISSUE THREAD

**Issue by devast8a** [douglascrockford/DEC64#33]
I found this while trying to diagnose #32.

```
#define D64(x, y) (((x) << 8) | ((y) & 0xFF))
dec64 a = dec64_divide(dec64_new(36040, 0), D64(1898420396013486ULL, -13));
dec64 b = dec64_divide(dec64_new(3604, 1),  D64(1898420396013486ULL, -13));
```

The values of a and b will be different (18984203960134854e-14 and 18984203960134855e-14 respectively) despite the inputs being the same number but with different representations. I have to use `D64` here to create the second value because `dec64_new` will change the value in such a way that it breaks this reproduction of the bug. The value can be obtained through only calls to `dec64_divide`, `dec64_add`, and `dec64_new`.

**Comment by douglascrockford** [comment]
Please submit a fix.
