### ISSUE TITLE
nasm version still valid?

### ISSUE THREAD

**Issue by newbie-02** [douglascrockford/DEC64#35]
Is the 'nasm' version for linux supposed / tested to work with actual systems? 
'gcc (Debian 13.3.0-5) 13.3.0' 

I'm not an expert, 'me bad' is always an option, get compiler warnings about: 
```
/usr/bin/ld: warning: dec64.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```
And dec64_test.c produces 263 fails, starting with: 
```
FAIL abs: nan
a                      nan
?     -36028797018963968 nan
=                      nan

FAIL abs: nonnan
a                      nan
?     -36028797018963968 nan
=                      nan

pass abs: zero
a                      0
=                      0
```

TIA for any hints :-)

**Comment by douglascrockford** [comment]
There is no nasm version. It was developed for masm. I have only tested on Windows, as documented.

The math package is a placeholder. It should be replaced with something faster and more accurate.

**Comment by newbie-02** [comment]
From the README ( at the bottom ): 

`A NASM port of dec64.asm is available at https://gist.github.com/jamesdiacono/bc9337520727876e09bafaf98225019c, which passes the tests on Linux and MacOS.` 
 
 Think it would be meaningful to care for, think you'll rather find linux freaks interested in alternate computing and alternate datatypes than windows sheep.

**Comment by douglascrockford** [comment]
You might want to talk to James about the nasm port.
