### ISSUE TITLE
MATH: basic: min and max values not balanced

### ISSUE THREAD

**Issue by newbie-02** [douglascrockford/DEC64#36]
besides the value ranges of most computer math system being pure overkill,  
there is a meaningful requirement in IEEE 754 to have small and big values balanced,  
in a way that very big values still have multiplication inverses with full precision.  
DEC64 has about 16 decimal ranges not covered by multiplication inverses, and another  
16 decimal ranges ( above 1E+111 ) having multiplication inverses with reduced 
precision ( denormals ).  
Assume it's known and well considered, but may be 'unintuitive' for acceptance as  
replacement ... ???

**Comment by douglascrockford** [comment]
There are always tradeoffs. I felt it was more important that 0.1 + 0.2 produce the correct result.

**Comment by newbie-02** [comment]
completely correct, and I welcome any efforts in that direction. But it could also have been achieved with a shifted exponent? -143 .. +111 which together with the 16 digits of the significand gives a balanced ratio?

**Comment by douglascrockford** [comment]
In most applications, when you go past +20, it is likely because your program is in error. So I do not see a benefit to balance in the extremities.

**Comment by newbie-02** [comment]
This would suggest a design with 58 bit coefficient and 6 bit exponent, full 17 digits of precision, and 63 shifted by -47 as exponent, 63 for infinity and NaN, infinity greater than max, effectively -47 ... +15 as exponent for normal values, plus 16 ranges from coefficient, about ~1E-31 ... ~1E+31 effective values with full precision, balanced, and a range span to inflate a Planck length to the size of the universe, in centimetres both values 17 digits precise ;-)  
Over 10 million different ‘normal’ integers for every living human being for date of birth, passport, address, bank accounts, credit cards, social security, telephone, IP, ... nice overkill ... money values exact up to a quadrillion ...  

To be clear, I'm not! suggesting a redesign because of this, but to think about it should a redesign become necessary at some point for other reasons.
